version: "3.9"

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: octo-events
  cache:
    image: redis
    ports:
      - 6379:6379